### ISSUE TITLE
which implement SfSNet using pytorch did you use?

### ISSUE THREAD

**Issue by Iam-Jane** [andrewhou1/GeomConsistentFR#15]
Hi, I find there are some implements SfSNet using pytorch. 
Could you tell me which one did you use in the paper? @andrewhou1

**Comment by andrewhou1** [comment]
Hi there,

Thanks for your interest in our work! So at the time, I emailed the authors of SfSNet and they handed me a pytorch implementation. Specifically, I emailed Soumyadip Sengupta, who is now a professor at the University of North Carolina-Chapel Hill. If any of the pytorch implementations are from him or his coauthors, it's probably that one. Alternatively, perhaps you can email him for it.

**Comment by Iam-Jane** [comment]
OK，I will try later. Thank you～^_^



发自我的iPhone


------------------ Original ------------------
From: andrewhou1 ***@***.***&gt;
Date: Mon,May 22,2023 10:26 AM
To: andrewhou1/GeomConsistentFR ***@***.***&gt;
Cc: Jing Bao ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [andrewhou1/GeomConsistentFR] which implement SfSNet usingpytorch did you use? (Issue #15)





 
Hi there,
 
Thanks for your interest in our work! So at the time, I emailed the authors of SfSNet and they handed me a pytorch implementation. Specifically, I emailed Soumyadip Sengupta, who is now a professor at the University of North Carolina-Chapel Hill. If any of the pytorch implementations are from him or his coauthors, it's probably that one. Alternatively, perhaps you can email him for it.
