### ISSUE TITLE
Transfer lightning

### ISSUE THREAD

**Issue by Donkdot** [andrewhou1/GeomConsistentFR#2]
Hello! Amazing job! I’m sorry to disturb you in your busy schedule. I’m a student of Shenzhen University from China.  I want to relight images through reference images, but I don’t know how to do that . If possible, can you teach me how to do that? 
I would appreciate it if you could help me.
Thanks and regards!

**Comment by wrainbow0705** [comment]
Have you solved this problem?I want to transfer reference image's lighting to target image,too.

**Comment by Donkdot** [comment]
I send email to the author，he said he will upload the code for lighting transfer later. ^_^

**Comment by andrewhou1** [comment]
Hi there,

Thanks for your interest in our work! I've uploaded the lighting transfer testing code and model as well as some updates to the instructions in the Testing section for how to run the lighting transfer code. The python file of interest is "test_relight_single_image_lighting_transfer.py". I will also upload the training code for lighting transfer, as it is a separately trained model from the model with fixed lighting parameters (target lightings).

**Comment by Donkdot** [comment]
Thanks a lot!

**Comment by Donkdot** [comment]
Sorry to disturb you, I wonder can I use the input mask from MP_data you provide or use the face_parsing? I try the lighting transfe code, the result is not good, and there is some black pixels, I use the fix_border_artifacts_CVPR2022.m to fix it, but the result is almost unchanged.

**Comment by Donkdot** [comment]
I test the method on CelebAHQ-dataset.

**Comment by andrewhou1** [comment]
Did you use the mask from CelebAHQ_face_masks/? Those masks involve the whole face. Also yes, in my experiments I often found the lighting transfer performance is not as good as the performance when the user fixes the lighting. We rely heavily on the SfSNet method to supervise the lighting estimation, which is not always accurate for directional lighting. Our method's lighting estimation is therefore impacted by this.

**Comment by Donkdot** [comment]
Yes，I used the mask from CelebAHQ_face_masks. I will try some other lighting estimation approach. Thank you so much for replying me!
