### ISSUE TITLE
transfer illumination from a reference image to target image

### ISSUE THREAD

**Issue by wrainbow0705** [andrewhou1/GeomConsistentFR#3]
Very wonderful research.
I was wondering how do I transfer the lighting from a reference image to the target image?
All I can find is the fixed lighting parameters from test_relight_single_image.py.
Could you tell me what to do?Thanks.

**Comment by andrewhou1** [comment]
Hi there,

Thanks for your interest in our work! I've uploaded the lighting transfer testing code and model as well as some updates to the instructions in the Testing section for how to run the lighting transfer code. The python file of interest is "test_relight_single_image_lighting_transfer.py". I will also upload the training code for lighting transfer, as it is a separately trained model from the model with fixed lighting parameters (target lightings).

**Comment by wrainbow0705** [comment]
Thanks a lot!
